### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [TheReactiveMouse/MARCH-W#6]
Советую тебе до конца прочитать моё сообщение к тебе, а не игнорить и кидать в ЧС (если на GitHub'е есть такая функция). Я лишь хочу выговориться насчёт возникшей ситуации, а что делать со мной ты решишь сам.

Мыш... Привет. Послушай, я хочу тебе кое-что сказать. Я извиняюсь за свой, ну... Меня немного прибомбило тогда с твоих слов. А так как ты знаешь, что я вспылчивый, то... ну... меня легко взбесить. Я не знаю, что тебе так зацепило, что ты до сих пор держишь на меня такую сильную злобу, что аж называешь меня "психопатом" (а это, честно говоря, слышать обидно от приятеля, с которым у меня очень много общего). Даже у меня больше преданности.

Несмотря на то, что я токсик, я очень преданный друг. Тот же Мури… Я считаю его своим лучшим другом (я честно говоря, хз, кто я для него сейчас, да и мне это малоинтересно). (И да, он меня не кинул в ЧС, да и навряд ли кинет). Сколько мы с ним ссорились (а в большинстве своём именно я и начинал срачи)… Хер ногу переломит. Но при этом всём, я всегда приходил к нему через время к нему извиняться. И он меня прощал… Не знаю почему, но всё-таки…

А с твоей стороны так вот поступить… Немного по-предательски… Хотя… Я сомневаюсь, что у тебя хоть когда-то будут друзья с таким-то поведением. Ты ведешь себя, как маленькая девочка – чуть тебя обидели, ты сразу кидаешь в ЧС и сильно обижаешься на всю жизнь. Ты моральный слабак, который не может дать словесный отпор, такому токсику, как я. Ты хотя бы научись игнорировать, тебе этот скилл уж точно пригодиться. Ты не принимаешь ни критики, ни советов, отмазываясь словами «Да мне плевать на международные стандарты программирования» и т. д.

Я хочу просто выговориться и всё. Мне уже немного плевать, что ты сделаешь. Я не против, вернуться к тому состоянию, когда мы были ещё приятелями, но если ты всё-таки решишь меня проигнорировать, то… Мне будет уже всё равно. И, если ты всё-таки дочитал до конца, то, если ты конечно хочешь, можешь ответить на мой один вопрос: как у тебя там с твоим MARCH-W?

_**My mind’s this cave
So dark, no moon, no stars
No sound, just hearts and walls of art**_

**Comment by TheReactiveMouse** [comment]
Отвечу на твой вопрос, и закрою данный вопрос. Ответ таков, делаю, планирую переписать полностью.
